version: '2'

services:
  th_bi-front:
    container_name: tropical-hazards-front
    build: .
    command: npm install --dev 
    volumes:
      - .:/tropical-hazards-frontend    
    external_links:
      - 20181tropicalhazardsbi_default
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=test
    networks:
      - default
